dist: bionic
language: r
cache:
  packages: true
latex: false
pandoc_version: 2.8.0.1

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0 PATH=$HOME/bin:$PATH

addons:
  apt:
    packages:
    - ghostscript

before_install:
  - wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
  - tlmgr --version

jobs:
  include:
    - r: release
      name: R release / Pandoc devel
      env: PATH=$HOME/bin:$PATH
      before_script:
        - wget -qO- https://github.com/rstudio/rmarkdown/raw/master/tools/install-pandoc.sh | sh
    - r: release
      name: R release / default Pandoc
